"""自动生成：Forebet 各场赛前预测（1X2 概率 / 预测比分 / 场均进球 / 赔率）。

请勿手工编辑。由 scripts_gen_forebet.py 抓取 forebet.com 列表页解析生成。
数据来源：forebet.com。
"""

null = None  # 兼容 JSON 字面量中的 null（缺失值）

FOREBET_RAW = [
    {
        "match_id": 2463153,
        "home_en": "Czech Republic",
        "away_en": "South Africa",
        "home_cn": "捷克",
        "away_cn": "南非",
        "url": "https://www.forebet.com/en/football/matches/czech-republic-south-africa-2463153",
        "p_home": 50,
        "p_draw": 29,
        "p_away": 21,
        "pred_sign": "1",
        "score_home": 2,
        "score_away": 0,
        "avg_goals": null,
        "venue": "Atlanta Stadium",
        "date": "18/06/2026 18:00",
        "odds_home": "-125",
        "odds_draw": "+260",
        "odds_away": "+350"
    },
    {
        "match_id": 2463156,
        "home_en": "Mexico",
        "away_en": "South Korea",
        "home_cn": "墨西哥",
        "away_cn": "韩国",
        "url": "https://www.forebet.com/en/football/matches/mexico-south-korea-2463156",
        "p_home": 44,
        "p_draw": 33,
        "p_away": 23,
        "pred_sign": "1",
        "score_home": null,
        "score_away": null,
        "avg_goals": null,
        "venue": "Guadalajara Stadium",
        "date": "19/06/2026 03:00",
        "odds_home": "+110",
        "odds_draw": "+220",
        "odds_away": "+275"
    },
    {
        "match_id": 2463155,
        "home_en": "Canada",
        "away_en": "Qatar",
        "home_cn": "加拿大",
        "away_cn": "卡塔尔",
        "url": "https://www.forebet.com/en/football/matches/canada-qatar-2463155",
        "p_home": 52,
        "p_draw": 35,
        "p_away": 13,
        "pred_sign": "1",
        "score_home": 2,
        "score_away": 0,
        "avg_goals": 2.25,
        "venue": "Vancouver Stadium",
        "date": "19/06/2026 00:00",
        "odds_home": "-357",
        "odds_draw": "+475",
        "odds_away": "+900"
    },
    {
        "match_id": 2463178,
        "home_en": "Bosnia-Herzegovina",
        "away_en": "Qatar",
        "home_cn": "波黑",
        "away_cn": "卡塔尔",
        "url": "https://www.forebet.com/en/football/matches/bosnia-herzegovina-qatar-2463178",
        "p_home": 50,
        "p_draw": 32,
        "p_away": 18,
        "pred_sign": "1",
        "score_home": 2,
        "score_away": 0,
        "avg_goals": 2.15,
        "venue": "Seattle Stadium",
        "date": "24/06/2026 21:00",
        "odds_home": "-238",
        "odds_draw": "+400",
        "odds_away": "+550"
    },
    {
        "match_id": 2463157,
        "home_en": "USA",
        "away_en": "Australia",
        "home_cn": "美国",
        "away_cn": "澳大利亚",
        "url": "https://www.forebet.com/en/football/matches/usa-australia-2463157",
        "p_home": 43,
        "p_draw": 31,
        "p_away": 27,
        "pred_sign": "1",
        "score_home": 1,
        "score_away": 0,
        "avg_goals": null,
        "venue": "Seattle Stadium",
        "date": "19/06/2026 21:00",
        "odds_home": "-182",
        "odds_draw": "+333",
        "odds_away": "+450"
    },
    {
        "match_id": 2463159,
        "home_en": "Brazil",
        "away_en": "Haiti",
        "home_cn": "巴西",
        "away_cn": "海地",
        "url": "https://www.forebet.com/en/football/matches/brazil-haiti-2463159",
        "p_home": 74,
        "p_draw": 16,
        "p_away": 10,
        "pred_sign": "1",
        "score_home": 4,
        "score_away": 0,
        "avg_goals": null,
        "venue": "Philadelphia Stadium",
        "date": "20/06/2026 02:30",
        "odds_home": "-1250",
        "odds_draw": "+1000",
        "odds_away": "+2200"
    },
    {
        "match_id": 2463180,
        "home_en": "Morocco",
        "away_en": "Haiti",
        "home_cn": "摩洛哥",
        "away_cn": "海地",
        "url": "https://www.forebet.com/en/football/matches/morocco-haiti-2463180",
        "p_home": 38,
        "p_draw": 32,
        "p_away": 30,
        "pred_sign": "1",
        "score_home": 1,
        "score_away": 0,
        "avg_goals": 0.17,
        "venue": "Atlanta Stadium",
        "date": "25/06/2026 00:00",
        "odds_home": "-625",
        "odds_draw": "+650",
        "odds_away": "+1400"
    },
    {
        "match_id": 2463162,
        "home_en": "Germany",
        "away_en": "Ivory Coast",
        "home_cn": "德国",
        "away_cn": "科特迪瓦",
        "url": "https://www.forebet.com/en/football/matches/germany-ivory-coast-2463162",
        "p_home": 60,
        "p_draw": 28,
        "p_away": 12,
        "pred_sign": "1",
        "score_home": 3,
        "score_away": 0,
        "avg_goals": null,
        "venue": "Toronto Stadium",
        "date": "20/06/2026 22:00",
        "odds_home": "-227",
        "odds_draw": "+375",
        "odds_away": "+550"
    },
    {
        "match_id": 2463186,
        "home_en": "Japan",
        "away_en": "Sweden",
        "home_cn": "日本",
        "away_cn": "瑞典",
        "url": "https://www.forebet.com/en/football/matches/japan-sweden-2463186",
        "p_home": 39,
        "p_draw": 30,
        "p_away": 31,
        "pred_sign": "1",
        "score_home": 1,
        "score_away": 0,
        "avg_goals": 1.35,
        "venue": "Dallas Stadium",
        "date": "26/06/2026 01:00",
        "odds_home": "-105",
        "odds_draw": "+250",
        "odds_away": "+290"
    },
    {
        "match_id": 2463165,
        "home_en": "Spain",
        "away_en": "Saudi Arabia",
        "home_cn": "西班牙",
        "away_cn": "沙特阿拉伯",
        "url": "https://www.forebet.com/en/football/matches/spain-saudi-arabia-2463165",
        "p_home": 43,
        "p_draw": 37,
        "p_away": 20,
        "pred_sign": "1",
        "score_home": 2,
        "score_away": 0,
        "avg_goals": 2.25,
        "venue": "Atlanta Stadium",
        "date": "21/06/2026 18:00",
        "odds_home": "-1000",
        "odds_draw": "+900",
        "odds_away": "+2200"
    },
    {
        "match_id": 2463167,
        "home_en": "Uruguay",
        "away_en": "Cape Verde",
        "home_cn": "乌拉圭",
        "away_cn": "佛得角",
        "url": "https://www.forebet.com/en/football/matches/uruguay-cape-verde-2463167",
        "p_home": 42,
        "p_draw": 32,
        "p_away": 26,
        "pred_sign": "1",
        "score_home": 1,
        "score_away": 0,
        "avg_goals": 1.1,
        "venue": "Miami Stadium",
        "date": "22/06/2026 00:00",
        "odds_home": "-250",
        "odds_draw": "+333",
        "odds_away": "+800"
    },
    {
        "match_id": 2463192,
        "home_en": "Cape Verde",
        "away_en": "Saudi Arabia",
        "home_cn": "佛得角",
        "away_cn": "沙特阿拉伯",
        "url": "https://www.forebet.com/en/football/matches/cape-verde-saudi-arabia-2463192",
        "p_home": 37,
        "p_draw": 33,
        "p_away": 31,
        "pred_sign": "1",
        "score_home": 1,
        "score_away": 0,
        "avg_goals": 1.25,
        "venue": "Houston Stadium",
        "date": "27/06/2026 02:00",
        "odds_home": "+135",
        "odds_draw": "+250",
        "odds_away": "+190"
    },
    {
        "match_id": 2463166,
        "home_en": "Belgium",
        "away_en": "Iran",
        "home_cn": "比利时",
        "away_cn": "伊朗",
        "url": "https://www.forebet.com/en/football/matches/belgium-iran-2463166",
        "p_home": 45,
        "p_draw": 31,
        "p_away": 24,
        "pred_sign": "1",
        "score_home": 2,
        "score_away": 1,
        "avg_goals": 2.63,
        "venue": "Los Angeles Stadium",
        "date": "21/06/2026 21:00",
        "odds_home": "-250",
        "odds_draw": "+375",
        "odds_away": "+700"
    },
    {
        "match_id": 2463170,
        "home_en": "France",
        "away_en": "Iraq",
        "home_cn": "法国",
        "away_cn": "伊拉克",
        "url": "https://www.forebet.com/en/football/matches/france-iraq-2463170",
        "p_home": 70,
        "p_draw": 21,
        "p_away": 9,
        "pred_sign": "1",
        "score_home": 3,
        "score_away": 0,
        "avg_goals": 3.45,
        "venue": "Philadelphia Stadium",
        "date": "22/06/2026 23:00",
        "odds_home": "-1429",
        "odds_draw": "+1100",
        "odds_away": "+2800"
    },
    {
        "match_id": 2463169,
        "home_en": "Argentina",
        "away_en": "Austria",
        "home_cn": "阿根廷",
        "away_cn": "奥地利",
        "url": "https://www.forebet.com/en/football/matches/argentina-austria-2463169",
        "p_home": 56,
        "p_draw": 30,
        "p_away": 14,
        "pred_sign": "1",
        "score_home": 2,
        "score_away": 0,
        "avg_goals": 2.25,
        "venue": "Dallas Stadium",
        "date": "22/06/2026 19:00",
        "odds_home": "-222",
        "odds_draw": "+333",
        "odds_away": "+650"
    },
    {
        "match_id": 2463173,
        "home_en": "Portugal",
        "away_en": "Uzbekistan",
        "home_cn": "葡萄牙",
        "away_cn": "乌兹别克斯坦",
        "url": "https://www.forebet.com/en/football/matches/portugal-uzbekistan-2463173",
        "p_home": 57,
        "p_draw": 23,
        "p_away": 21,
        "pred_sign": "1",
        "score_home": 2,
        "score_away": 1,
        "avg_goals": 2.73,
        "venue": "Houston Stadium",
        "date": "23/06/2026 19:00",
        "odds_home": "-556",
        "odds_draw": "+600",
        "odds_away": "+1400"
    },
    {
        "match_id": 2463174,
        "home_en": "England",
        "away_en": "Ghana",
        "home_cn": "英格兰",
        "away_cn": "加纳",
        "url": "https://www.forebet.com/en/football/matches/england-ghana-2463174",
        "p_home": 75,
        "p_draw": 14,
        "p_away": 11,
        "pred_sign": "1",
        "score_home": 3,
        "score_away": 0,
        "avg_goals": 3.15,
        "venue": "Boston Stadium",
        "date": "23/06/2026 22:00",
        "odds_home": "-500",
        "odds_draw": "+600",
        "odds_away": "+1200"
    },
    {
        "match_id": 2463129,
        "home_en": "Mexico",
        "away_en": "South Africa",
        "home_cn": "墨西哥",
        "away_cn": "南非",
        "url": "https://www.forebet.com/en/football/matches/mexico-south-africa-2463129",
        "p_home": 61,
        "p_draw": 28,
        "p_away": 11,
        "pred_sign": "1",
        "score_home": 2,
        "score_away": 1,
        "avg_goals": 2.75,
        "venue": "Mexico City Stadium",
        "date": "11/06/2026 21:00",
        "odds_home": "-238",
        "odds_draw": "+333",
        "odds_away": "+750"
    },
    {
        "match_id": 2463131,
        "home_en": "Canada",
        "away_en": "Bosnia-Herzegovina",
        "home_cn": "加拿大",
        "away_cn": "波黑",
        "url": "https://www.forebet.com/en/football/matches/canada-bosnia-herzegovina-2463131",
        "p_home": 41,
        "p_draw": 35,
        "p_away": 24,
        "pred_sign": "1",
        "score_home": 1,
        "score_away": 0,
        "avg_goals": null,
        "venue": "Toronto Stadium",
        "date": "12/06/2026 21:00",
        "odds_home": "-125",
        "odds_draw": "+250",
        "odds_away": "+375"
    },
    {
        "match_id": 2463132,
        "home_en": "USA",
        "away_en": "Paraguay",
        "home_cn": "美国",
        "away_cn": "巴拉圭",
        "url": "https://www.forebet.com/en/football/matches/usa-paraguay-2463132",
        "p_home": 45,
        "p_draw": 37,
        "p_away": 18,
        "pred_sign": "1",
        "score_home": 1,
        "score_away": 0,
        "avg_goals": 1.25,
        "venue": "Los Angeles Stadium",
        "date": "13/06/2026 03:00",
        "odds_home": "+105",
        "odds_draw": "+230",
        "odds_away": "+280"
    },
    {
        "match_id": 2463134,
        "home_en": "Brazil",
        "away_en": "Morocco",
        "home_cn": "巴西",
        "away_cn": "摩洛哥",
        "url": "https://www.forebet.com/en/football/matches/brazil-morocco-2463134",
        "p_home": 59,
        "p_draw": 27,
        "p_away": 14,
        "pred_sign": "1",
        "score_home": 3,
        "score_away": 1,
        "avg_goals": 3.29,
        "venue": "New York New Jersey Stadium",
        "date": "14/06/2026 00:00",
        "odds_home": "-154",
        "odds_draw": "+280",
        "odds_away": "+450"
    },
    {
        "match_id": 2463138,
        "home_en": "Netherlands",
        "away_en": "Japan",
        "home_cn": "荷兰",
        "away_cn": "日本",
        "url": "https://www.forebet.com/en/football/matches/netherlands-japan-2463138",
        "p_home": 48,
        "p_draw": 23,
        "p_away": 28,
        "pred_sign": "1",
        "score_home": 2,
        "score_away": 0,
        "avg_goals": 2.0,
        "venue": "Dallas Stadium",
        "date": "14/06/2026 22:00",
        "odds_home": "+110",
        "odds_draw": "+240",
        "odds_away": "+260"
    },
    {
        "match_id": 2463141,
        "home_en": "Spain",
        "away_en": "Cape Verde",
        "home_cn": "西班牙",
        "away_cn": "佛得角",
        "url": "https://www.forebet.com/en/football/matches/spain-cape-verde-2463141",
        "p_home": 75,
        "p_draw": 16,
        "p_away": 9,
        "pred_sign": "1",
        "score_home": 3,
        "score_away": 0,
        "avg_goals": 3.25,
        "venue": "Atlanta Stadium",
        "date": "15/06/2026 18:00",
        "odds_home": "-1667",
        "odds_draw": "+1400",
        "odds_away": "+2200"
    },
    {
        "match_id": 2463142,
        "home_en": "Belgium",
        "away_en": "Egypt",
        "home_cn": "比利时",
        "away_cn": "埃及",
        "url": "https://www.forebet.com/en/football/matches/belgium-egypt-2463142",
        "p_home": 50,
        "p_draw": 28,
        "p_away": 22,
        "pred_sign": "1",
        "score_home": 1,
        "score_away": 0,
        "avg_goals": null,
        "venue": "Seattle Stadium",
        "date": "15/06/2026 21:00",
        "odds_home": "-200",
        "odds_draw": "+320",
        "odds_away": "+550"
    },
    {
        "match_id": 2463144,
        "home_en": "Iran",
        "away_en": "New Zealand",
        "home_cn": "伊朗",
        "away_cn": "新西兰",
        "url": "https://www.forebet.com/en/football/matches/iran-new-zealand-2463144",
        "p_home": 48,
        "p_draw": 27,
        "p_away": 26,
        "pred_sign": "1",
        "score_home": 2,
        "score_away": 0,
        "avg_goals": 1.5,
        "venue": "Los Angeles Stadium",
        "date": "16/06/2026 03:00",
        "odds_home": "-118",
        "odds_draw": "+240",
        "odds_away": "+350"
    },
    {
        "match_id": 2463145,
        "home_en": "France",
        "away_en": "Senegal",
        "home_cn": "法国",
        "away_cn": "塞内加尔",
        "url": "https://www.forebet.com/en/football/matches/france-senegal-2463145",
        "p_home": 47,
        "p_draw": 28,
        "p_away": 25,
        "pred_sign": "1",
        "score_home": 2,
        "score_away": 0,
        "avg_goals": 1.71,
        "venue": "New York New Jersey Stadium",
        "date": "16/06/2026 21:00",
        "odds_home": "-222",
        "odds_draw": "+360",
        "odds_away": "+600"
    },
    {
        "match_id": 2463147,
        "home_en": "Argentina",
        "away_en": "Algeria",
        "home_cn": "阿根廷",
        "away_cn": "阿尔及利亚",
        "url": "https://www.forebet.com/en/football/matches/argentina-algeria-2463147",
        "p_home": 57,
        "p_draw": 33,
        "p_away": 10,
        "pred_sign": "1",
        "score_home": 2,
        "score_away": 0,
        "avg_goals": 1.5,
        "venue": "Kansas City Stadium",
        "date": "17/06/2026 03:00",
        "odds_home": "-182",
        "odds_draw": "+300",
        "odds_away": "+550"
    },
    {
        "match_id": 2463148,
        "home_en": "Austria",
        "away_en": "Jordan",
        "home_cn": "奥地利",
        "away_cn": "约旦",
        "url": "https://www.forebet.com/en/football/matches/austria-jordan-2463148",
        "p_home": 54,
        "p_draw": 34,
        "p_away": 12,
        "pred_sign": "1",
        "score_home": 1,
        "score_away": 0,
        "avg_goals": 1.25,
        "venue": "San Francisco Bay Area Stadium",
        "date": "17/06/2026 06:00",
        "odds_home": "-250",
        "odds_draw": "+375",
        "odds_away": "+700"
    },
    {
        "match_id": 2463149,
        "home_en": "Portugal",
        "away_en": "DR Congo",
        "home_cn": "葡萄牙",
        "away_cn": "刚果民主共和国",
        "url": "https://www.forebet.com/en/football/matches/portugal-dr-congo-2463149",
        "p_home": 59,
        "p_draw": 28,
        "p_away": 13,
        "pred_sign": "1",
        "score_home": 2,
        "score_away": 0,
        "avg_goals": null,
        "venue": "Houston Stadium",
        "date": "17/06/2026 19:00",
        "odds_home": "-400",
        "odds_draw": "+475",
        "odds_away": "+1100"
    },
    {
        "match_id": 2463150,
        "home_en": "England",
        "away_en": "Croatia",
        "home_cn": "英格兰",
        "away_cn": "克罗地亚",
        "url": "https://www.forebet.com/en/football/matches/england-croatia-2463150",
        "p_home": 38,
        "p_draw": 31,
        "p_away": 30,
        "pred_sign": "1",
        "score_home": 2,
        "score_away": 1,
        "avg_goals": null,
        "venue": "Dallas Stadium",
        "date": "17/06/2026 22:00",
        "odds_home": "-143",
        "odds_draw": "+275",
        "odds_away": "+400"
    },
    {
        "match_id": 2463151,
        "home_en": "Ghana",
        "away_en": "Panama",
        "home_cn": "加纳",
        "away_cn": "巴拿马",
        "url": "https://www.forebet.com/en/football/matches/ghana-panama-2463151",
        "p_home": 42,
        "p_draw": 32,
        "p_away": 26,
        "pred_sign": "1",
        "score_home": null,
        "score_away": null,
        "avg_goals": null,
        "venue": "Toronto Stadium",
        "date": "18/06/2026 01:00",
        "odds_home": "+130",
        "odds_draw": "+220",
        "odds_away": "+225"
    }
]
